// Generated by gencpp from file sensor_stack/convert_to_quaternion.msg
// DO NOT EDIT!


#ifndef SENSOR_STACK_MESSAGE_CONVERT_TO_QUATERNION_H
#define SENSOR_STACK_MESSAGE_CONVERT_TO_QUATERNION_H

#include <ros/service_traits.h>


#include <sensor_stack/convert_to_quaternionRequest.h>
#include <sensor_stack/convert_to_quaternionResponse.h>


namespace sensor_stack
{

struct convert_to_quaternion
{

typedef convert_to_quaternionRequest Request;
typedef convert_to_quaternionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct convert_to_quaternion
} // namespace sensor_stack


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sensor_stack::convert_to_quaternion > {
  static const char* value()
  {
    return "ac32c4b515e2f652841f785534a95f15";
  }

  static const char* value(const ::sensor_stack::convert_to_quaternion&) { return value(); }
};

template<>
struct DataType< ::sensor_stack::convert_to_quaternion > {
  static const char* value()
  {
    return "sensor_stack/convert_to_quaternion";
  }

  static const char* value(const ::sensor_stack::convert_to_quaternion&) { return value(); }
};


// service_traits::MD5Sum< ::sensor_stack::convert_to_quaternionRequest> should match
// service_traits::MD5Sum< ::sensor_stack::convert_to_quaternion >
template<>
struct MD5Sum< ::sensor_stack::convert_to_quaternionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sensor_stack::convert_to_quaternion >::value();
  }
  static const char* value(const ::sensor_stack::convert_to_quaternionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensor_stack::convert_to_quaternionRequest> should match
// service_traits::DataType< ::sensor_stack::convert_to_quaternion >
template<>
struct DataType< ::sensor_stack::convert_to_quaternionRequest>
{
  static const char* value()
  {
    return DataType< ::sensor_stack::convert_to_quaternion >::value();
  }
  static const char* value(const ::sensor_stack::convert_to_quaternionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sensor_stack::convert_to_quaternionResponse> should match
// service_traits::MD5Sum< ::sensor_stack::convert_to_quaternion >
template<>
struct MD5Sum< ::sensor_stack::convert_to_quaternionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sensor_stack::convert_to_quaternion >::value();
  }
  static const char* value(const ::sensor_stack::convert_to_quaternionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensor_stack::convert_to_quaternionResponse> should match
// service_traits::DataType< ::sensor_stack::convert_to_quaternion >
template<>
struct DataType< ::sensor_stack::convert_to_quaternionResponse>
{
  static const char* value()
  {
    return DataType< ::sensor_stack::convert_to_quaternion >::value();
  }
  static const char* value(const ::sensor_stack::convert_to_quaternionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENSOR_STACK_MESSAGE_CONVERT_TO_QUATERNION_H
